### ISSUE TITLE
Running error with PyTorch 1.12.1

### ISSUE THREAD

**Issue by StevenTang1998** [microsoft/fastseq#121]
The following error occurs with PyTorch 1.12.1, but disappears with PyTorch 1.11.0

```
  File "/home/tangtianyi/transformers/src/transformers/models/encoder_decoder/modeling_encoder_decoder.py", line 26, in <module>
    from ...modeling_utils import PreTrainedModel
  File "/home/tangtianyi/transformers/src/transformers/modeling_utils.py", line 41, in <module>
    from .generation_utils import GenerationMixin
  File "/home/tangtianyi/transformers/src/transformers/generation_utils.py", line 29, in <module>
    from .generation_logits_process import (
  File "/home/tangtianyi/transformers/src/transformers/generation_logits_process.py", line 25, in <module>
    import ngram_repeat_block_cuda
ImportError: /home/tangtianyi/miniconda3/lib/python3.8/site-packages/ngram_repeat_block_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tangtianyi/model/pretrained_models.py", line 31, in <module>
    from transformers import AutoConfig, AutoModelForCausalLM, AutoModelForSeq2SeqLM, EncoderDecoderModel
  File "<frozen importlib._bootstrap>", line 1039, in _handle_fromlist
  File "/home/tangtianyi/transformers/src/transformers/utils/import_utils.py", line 948, in __getattr__
    value = getattr(module, name)
  File "/home/tangtianyi/transformers/src/transformers/utils/import_utils.py", line 947, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/home/tangtianyi/transformers/src/transformers/utils/import_utils.py", line 959, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.models.encoder_decoder.modeling_encoder_decoder because of the following error (look up to see its traceback):
/home/tangtianyi/miniconda3/lib/python3.8/site-packages/ngram_repeat_block_cuda.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZNK3c1010TensorImpl36is_contiguous_nondefault_policy_implENS_12MemoryFormatE

```

**Comment by feihugis** [comment]
@StevenTang1998 I have tested with PyTorch 1.12.1. It works well at my side.  It seems like you did not reinstall fastseq (uninstall fastseq first and install it again) after you changed the version of PyTorch.

**Comment by StevenTang1998** [comment]
thanks
